import type { VenueConfig } from './types';

export const venueConfigs: VenueConfig[] = [
  {
    type: 'retail',
    label: 'Розничный магазин',
    description: 'Супермаркеты, торговые центры, бутики и магазины',
    icon: 'ShoppingBag',
    color: 'from-blue-500 to-blue-600',
    features: [
      {
        id: 'people_counting',
        name: 'Подсчёт посетителей',
        description: 'Автоматический подсчёт входящих и выходящих людей в реальном времени',
        icon: 'Users',
        enabled: true,
        category: 'counting',
      },
      {
        id: 'heatmap',
        name: 'Тепловые карты',
        description: 'Визуализация зон наибольшей активности покупателей',
        icon: 'Flame',
        enabled: true,
        category: 'tracking',
      },
      {
        id: 'theft_detection',
        name: 'Детекция краж',
        description: 'Распознавание подозрительного поведения и попыток кражи',
        icon: 'ShieldAlert',
        enabled: true,
        category: 'detection',
      },
      {
        id: 'queue_management',
        name: 'Управление очередями',
        description: 'Мониторинг длины очередей и времени ожидания',
        icon: 'Clock',
        enabled: true,
        category: 'business',
      },
      {
        id: 'customer_demographics',
        name: 'Демография клиентов',
        description: 'Анализ возраста и пола посетителей (анонимно)',
        icon: 'PieChart',
        enabled: false,
        category: 'business',
      },
      {
        id: 'shelf_monitoring',
        name: 'Мониторинг полок',
        description: 'Отслеживание наполненности полок и витрин',
        icon: 'Package',
        enabled: false,
        category: 'detection',
      },
    ],
  },
  {
    type: 'restaurant',
    label: 'Ресторан / Кафе',
    description: 'Рестораны, кафе, бары, фуд-корты и столовые',
    icon: 'UtensilsCrossed',
    color: 'from-orange-500 to-orange-600',
    features: [
      {
        id: 'table_occupancy',
        name: 'Заполненность столов',
        description: 'Мониторинг свободных и занятых столов в реальном времени',
        icon: 'LayoutGrid',
        enabled: true,
        category: 'tracking',
      },
      {
        id: 'wait_time',
        name: 'Время ожидания',
        description: 'Анализ времени ожидания обслуживания гостей',
        icon: 'Timer',
        enabled: true,
        category: 'business',
      },
      {
        id: 'staff_efficiency',
        name: 'Эффективность персонала',
        description: 'Анализ работы официантов и персонала кухни',
        icon: 'TrendingUp',
        enabled: true,
        category: 'business',
      },
      {
        id: 'hygiene_monitoring',
        name: 'Контроль гигиены',
        description: 'Мониторинг соблюдения санитарных норм на кухне',
        icon: 'Sparkles',
        enabled: true,
        category: 'safety',
      },
      {
        id: 'food_waste',
        name: 'Контроль отходов',
        description: 'Анализ пищевых отходов и оптимизация порций',
        icon: 'Trash2',
        enabled: false,
        category: 'business',
      },
      {
        id: 'customer_satisfaction',
        name: 'Удовлетворённость гостей',
        description: 'Анализ эмоций и поведения гостей',
        icon: 'Smile',
        enabled: false,
        category: 'business',
      },
    ],
  },
  {
    type: 'warehouse',
    label: 'Склад / Производство',
    description: 'Складские помещения, цеха, производственные линии',
    icon: 'Warehouse',
    color: 'from-green-500 to-green-600',
    features: [
      {
        id: 'safety_compliance',
        name: 'Охрана труда',
        description: 'Контроль ношения СИЗ и соблюдения техники безопасности',
        icon: 'HardHat',
        enabled: true,
        category: 'safety',
      },
      {
        id: 'inventory_tracking',
        name: 'Отслеживание инвентаря',
        description: 'Контроль перемещения товаров и инвентаря',
        icon: 'Package',
        enabled: true,
        category: 'tracking',
      },
      {
        id: 'restricted_area',
        name: 'Контроль зон доступа',
        description: 'Мониторинг доступа в ограниченные зоны',
        icon: 'Lock',
        enabled: true,
        category: 'safety',
      },
      {
        id: 'vehicle_monitoring',
        name: 'Мониторинг транспорта',
        description: 'Отслеживание погрузчиков и транспортных средств',
        icon: 'Truck',
        enabled: true,
        category: 'tracking',
      },
      {
        id: 'fire_detection',
        name: 'Детекция огня/дыма',
        description: 'Раннее обнаружение возгорания и задымления',
        icon: 'Flame',
        enabled: true,
        category: 'detection',
      },
      {
        id: 'productivity',
        name: 'Анализ производительности',
        description: 'Оценка эффективности рабочих процессов',
        icon: 'BarChart3',
        enabled: false,
        category: 'business',
      },
    ],
  },
  {
    type: 'office',
    label: 'Офис',
    description: 'Бизнес-центры, коворкинги, офисные помещения',
    icon: 'Building2',
    color: 'from-purple-500 to-purple-600',
    features: [
      {
        id: 'attendance',
        name: 'Учёт посещаемости',
        description: 'Автоматический учёт времени прихода и ухода сотрудников',
        icon: 'UserCheck',
        enabled: true,
        category: 'tracking',
      },
      {
        id: 'room_utilization',
        name: 'Загрузка переговорок',
        description: 'Мониторинг использования переговорных комнат',
        icon: 'DoorOpen',
        enabled: true,
        category: 'business',
      },
      {
        id: 'security_alerts',
        name: 'Охранные оповещения',
        description: 'Мгновенные оповещения о нарушениях безопасности',
        icon: 'Bell',
        enabled: true,
        category: 'detection',
      },
      {
        id: 'workspace_analytics',
        name: 'Аналитика рабочих мест',
        description: 'Анализ использования рабочего пространства',
        icon: 'BarChart3',
        enabled: true,
        category: 'business',
      },
      {
        id: 'visitor_management',
        name: 'Управление посетителями',
        description: 'Регистрация и отслеживание посетителей офиса',
        icon: 'UserPlus',
        enabled: false,
        category: 'tracking',
      },
      {
        id: 'energy_optimization',
        name: 'Энергоэффективность',
        description: 'Оптимизация освещения и климата на основе присутствия',
        icon: 'Zap',
        enabled: false,
        category: 'business',
      },
    ],
  },
  {
    type: 'bank',
    label: 'Банк / Финансы',
    description: 'Банковские отделения, обменные пункты, финансовые учреждения',
    icon: 'Landmark',
    color: 'from-yellow-500 to-yellow-600',
    features: [
      {
        id: 'suspicious_behavior',
        name: 'Подозрительное поведение',
        description: 'Детекция подозрительных действий и поведения',
        icon: 'AlertTriangle',
        enabled: true,
        category: 'detection',
      },
      {
        id: 'atm_monitoring',
        name: 'Мониторинг банкоматов',
        description: 'Контроль зоны банкоматов и детекция скиммеров',
        icon: 'CreditCard',
        enabled: true,
        category: 'detection',
      },
      {
        id: 'queue_analysis',
        name: 'Анализ очередей',
        description: 'Оптимизация работы окон обслуживания',
        icon: 'Users',
        enabled: true,
        category: 'business',
      },
      {
        id: 'face_recognition',
        name: 'Распознавание лиц',
        description: 'Идентификация VIP-клиентов и подозрительных лиц',
        icon: 'ScanFace',
        enabled: true,
        category: 'detection',
      },
      {
        id: 'loitering_detection',
        name: 'Детекция слоняния',
        description: 'Обнаружение длительного пребывания в зонах',
        icon: 'Eye',
        enabled: true,
        category: 'detection',
      },
      {
        id: 'cash_monitoring',
        name: 'Контроль кассовых операций',
        description: 'Видеоконтроль операций с наличными',
        icon: 'Banknote',
        enabled: false,
        category: 'safety',
      },
    ],
  },
  {
    type: 'parking',
    label: 'Парковка',
    description: 'Парковки, гаражи, автостоянки',
    icon: 'Car',
    color: 'from-cyan-500 to-cyan-600',
    features: [
      {
        id: 'license_plate',
        name: 'Распознавание номеров',
        description: 'Автоматическое считывание автомобильных номеров',
        icon: 'ScanLine',
        enabled: true,
        category: 'detection',
      },
      {
        id: 'space_occupancy',
        name: 'Заполненность парковки',
        description: 'Мониторинг свободных и занятых мест',
        icon: 'ParkingSquare',
        enabled: true,
        category: 'counting',
      },
      {
        id: 'traffic_flow',
        name: 'Транспортный поток',
        description: 'Анализ въезда/выезда и загруженности',
        icon: 'ArrowLeftRight',
        enabled: true,
        category: 'tracking',
      },
      {
        id: 'violation_detection',
        name: 'Детекция нарушений',
        description: 'Обнаружение неправильной парковки и нарушений',
        icon: 'AlertOctagon',
        enabled: true,
        category: 'detection',
      },
      {
        id: 'vehicle_classification',
        name: 'Классификация ТС',
        description: 'Определение типа транспортного средства',
        icon: 'Car',
        enabled: false,
        category: 'detection',
      },
      {
        id: 'dwell_time',
        name: 'Время пребывания',
        description: 'Отслеживание продолжительности стоянки',
        icon: 'Clock',
        enabled: true,
        category: 'tracking',
      },
    ],
  },
];
