#!/bin/bash
set -e

# ============================================
# CamAI SaaS — Deployment Script
# Запуск: bash scripts/deploy-saas.sh
# ============================================

echo "=== CamAI SaaS Deployment ==="
echo ""

# Check required env vars
if [ -z "$DOMAIN" ]; then
  read -p "Введите домен (например camai.uz): " DOMAIN
fi

if [ -z "$NEXTAUTH_SECRET" ]; then
  NEXTAUTH_SECRET=$(openssl rand -base64 32)
  echo "Сгенерирован NEXTAUTH_SECRET"
fi

if [ -z "$DB_PASSWORD" ]; then
  DB_PASSWORD=$(openssl rand -base64 16 | tr -d '=+/')
  echo "Сгенерирован DB_PASSWORD"
fi

# Create .env file
cat > .env << EOF
# CamAI SaaS — auto-generated by deploy script
DOMAIN=${DOMAIN}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=https://${DOMAIN}
DB_PASSWORD=${DB_PASSWORD}
PORT=3000
GEMINI_API_KEY=${GEMINI_API_KEY:-}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
EOF

echo ""
echo "[1/4] .env файл создан"

# Update Caddyfile with domain
cat > Caddyfile << EOF
${DOMAIN} {
	reverse_proxy app:3000
}
EOF

echo "[2/4] Caddyfile обновлён для ${DOMAIN}"

# Build and start
echo "[3/4] Сборка и запуск..."
docker compose -f docker-compose.saas.yml build
docker compose -f docker-compose.saas.yml up -d

# Wait for DB
echo "Ожидание БД..."
sleep 5

# Run migrations and seed plans
echo "[4/4] Миграции и seed планов..."
docker compose -f docker-compose.saas.yml exec app npx prisma migrate deploy
docker compose -f docker-compose.saas.yml exec app npx tsx prisma/seed-plans.ts

echo ""
echo "=== CamAI SaaS Deployed! ==="
echo ""
echo "URL:     https://${DOMAIN}"
echo "DB:      PostgreSQL (порт 5432, пароль в .env)"
echo ""
echo "Следующие шаги:"
echo "  1. Зарегистрируйте первый аккаунт на https://${DOMAIN}/register"
echo "  2. Для superadmin: установите role='superadmin' в БД"
echo "  3. Для Stripe: добавьте STRIPE_SECRET_KEY в .env"
echo "=========================="
